spring:
  application:
    name: LanAdvice Survey-API Spring
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:surveyapi}
    username: ${DB_USER:surveyapi}
    password: ${DB_PASSWORD:P@ssp0rt}
    driverClassName: org.postgresql.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 250MB
  mvc:
    log-request-details: true

logging.level.org.springframework.web: DEBUG

server:
  port: ${PORT:10000}

---
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://${DB_HOST:10.69.32.5}:${DB_PORT:5432}/${DB_NAME:surveyapi}
